'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FacturaDetalle
    Public Property id_cabeceraFactura As Integer
    Public Property codigo As String
    Public Property cantidad As Integer
    Public Property precio As Decimal

    Public Overridable Property FacturaCabecera As FacturaCabecera
    Public Overridable Property Productos As Productos

End Class
