'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FacturaCabecera
    Public Property id_cabeceraFactura As Integer
    Public Property DNI As String
    Public Property id_usuario As Integer
    Public Property fechaVenta As Date
    Public Property formaPago As String

    Public Overridable Property Clientes As Clientes
    Public Overridable Property Usuarios As Usuarios
    Public Overridable Property FacturaDetalle As FacturaDetalle

End Class
