'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class FemsportDataBaseEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=FemsportDataBaseEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Clientes() As DbSet(Of Clientes)
    Public Overridable Property Empleados() As DbSet(Of Empleados)
    Public Overridable Property FacturaCabecera() As DbSet(Of FacturaCabecera)
    Public Overridable Property FacturaDetalle() As DbSet(Of FacturaDetalle)
    Public Overridable Property Marcas() As DbSet(Of Marcas)
    Public Overridable Property Productos() As DbSet(Of Productos)
    Public Overridable Property TipoEmpleado() As DbSet(Of TipoEmpleado)
    Public Overridable Property TipoProducto() As DbSet(Of TipoProducto)
    Public Overridable Property Usuarios() As DbSet(Of Usuarios)

End Class
