'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Productos
    Public Property codigo As String
    Public Property id_marca As Integer
    Public Property id_tipoProducto As Integer
    Public Property precio As Decimal
    Public Property stock As Integer
    Public Property stockMinimo As Integer
    Public Property descripcion As String
    Public Property talle As String
    Public Property estado As String

    Public Overridable Property FacturaDetalle As ICollection(Of FacturaDetalle) = New HashSet(Of FacturaDetalle)
    Public Overridable Property Marcas As Marcas
    Public Overridable Property TipoProducto As TipoProducto

End Class
