'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TipoEmpleado
    Public Property id_tipoEmpleado As Integer
    Public Property Descripcion As String

    Public Overridable Property Empleados As ICollection(Of Empleados) = New HashSet(Of Empleados)

End Class
