'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Usuarios
    Public Property id_usuario As Integer
    Public Property CUIT As String
    Public Property usuario As String
    Public Property contraseña As String

    Public Overridable Property Empleados As Empleados
    Public Overridable Property FacturaCabecera As ICollection(Of FacturaCabecera) = New HashSet(Of FacturaCabecera)

End Class
