'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Femsport.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Customers() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Customers", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Edit_icon_icons_com_71853() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Edit_icon-icons.com_71853", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_Buy_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-Buy-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_Checkout_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-Checkout-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_Clear_Shopping_Cart_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-Clear Shopping Cart-48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_Clear_Shopping_Cart_481() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-Clear Shopping Cart-481", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_05_Tag_290145() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_05.Tag_290145", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_6_3319634() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_6_3319634", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_6_33196341() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_6_33196341", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_BT_printer_905556() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_BT_printer_905556", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_Close_1891023() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_Close_1891023", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_Confirm_40044() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_Confirm_40044", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_Confirm_400441() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_Confirm_400441", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_edit_change_pencil_2931178() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_edit-change-pencil_2931178", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_exit_2676937() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_exit_2676937", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_exit_26769371() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_exit_26769371", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_eye_preview_see_seen_view_392505() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_eye_preview_see_seen_view_392505", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_f_cross_256_282471() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_f-cross_256_282471", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_General___Office_37_1471104() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_General_-_Office_37_1471104", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_icon_111_search_314689() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_icon-111-search_314689", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_icon_111_search_3146891() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_icon-111-search_3146891", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_icon_111_search_3146892() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_icon-111-search_3146892", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_icon_111_search_3146893() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_icon-111-search_3146893", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_icon_ios7_people_211793() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_icon-ios7-people_211793", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_Info_Circle_Symbol_Information_Letter_1396823() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_Info_Circle_Symbol_Information_Letter_1396823", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_Info_Circle_Symbol_Information_Letter_13968231() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_Info_Circle_Symbol_Information_Letter_13968231", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_management_2799204__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_management_2799204 (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_more_476329() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_more_476329", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_new_24_103173() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_new-24_103173", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_new_24_1031731() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_new-24_1031731", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_office_41_809593() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_office-41_809593", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_office_41_8095931() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_office-41_8095931", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_questionssvg_1579793() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_questionssvg_1579793", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property if_sign_add_299068() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("if_sign-add_299068", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property login() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("login", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property loginok() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loginok", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property loginok500() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loginok500", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logo1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property logout_3622() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logout_3622", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mdis() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mdis", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mdis500() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mdis500", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mdis5001() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mdis5001", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mdis5002() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mdis5002", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property o14tpzA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("o14tpzA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ok_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ok-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pink_and_blue_png_gradient_blue_and_pink_by_vodkachanlovesyou_1024() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pink-and-blue-png-gradient-blue-and-pink-by-vodkachanlovesyou-1024", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pink_gradient_abstract_hd_wallpaper_1920x1080_4251() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pink-gradient-abstract-hd-wallpaper-1920x1080-4251", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pink_yellow_gradient_wallpaper_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pink-yellow-gradient-wallpaper-1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pink_yellow_gradient_wallpaper_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pink-yellow-gradient-wallpaper-11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pink_yellow_gradient_wallpaper_110() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pink-yellow-gradient-wallpaper-110", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pink_yellow_gradient_wallpaper_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pink-yellow-gradient-wallpaper-12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pink_yellow_gradient_wallpaper_13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pink-yellow-gradient-wallpaper-13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pink_yellow_gradient_wallpaper_14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pink-yellow-gradient-wallpaper-14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pink_yellow_gradient_wallpaper_15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pink-yellow-gradient-wallpaper-15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pink_yellow_gradient_wallpaper_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pink-yellow-gradient-wallpaper-16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pink_yellow_gradient_wallpaper_17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pink-yellow-gradient-wallpaper-17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pink_yellow_gradient_wallpaper_18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pink-yellow-gradient-wallpaper-18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pink_yellow_gradient_wallpaper_19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pink-yellow-gradient-wallpaper-19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Researching_and_Screening_Tenants_for_a_Santa_Clarita_Rental_Property() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Researching-and-Screening-Tenants-for-a-Santa-Clarita-Rental-Property", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property User_blue256_25016() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User-blue256_25016", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
